# messaging_app/chats/urls.py

from django.urls import path, include
from rest_framework import routers
from .views import ConversationViewSet, MessageViewSet

# Create a router instance
router = routers.DefaultRouter()

# Register the viewsets with the router
# This will automatically generate URLs for list, create, retrieve, update, delete
router.register(r'conversations', ConversationViewSet, basename='conversation')
router.register(r'messages', MessageViewSet, basename='message')

urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),
]