# Generated by Django 5.2.3 on 2025-07-30 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False, help_text='Indicates if this message has been edited.'),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last edit.', null=True),
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_content', models.TextField(help_text='The content of the message before the edit.')),
                ('edited_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this version was saved.')),
                ('edited_by', models.ForeignKey(blank=True, help_text='The user who performed this edit (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_messages_history', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(help_text='The original message this history entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='messaging.message')),
            ],
            options={
                'verbose_name': 'Message History',
                'verbose_name_plural': 'Message History',
                'ordering': ['edited_at'],
            },
        ),
    ]
