# This is the "blue" (current/stable) version of your Django app.
apiVersion: apps/v1
kind: Deployment
metadata:
  # Renamed for clarity in blue-green strategy
  name: django-messaging-app-blue-deployment
  labels:
    app: django-messaging-app-blue # Specific label for blue version
    app-version: blue # Another label to identify version
spec:
  replicas: 1 # Start with 1 replica for blue
  selector:
    matchLabels:
      app: django-messaging-app-blue
  template:
    metadata:
      labels:
        app: django-messaging-app-blue
        app-version: blue
    spec:
      containers:
      - name: django-messaging-app
        image: messaging_app-web:latest # Your Docker image for the blue version
        ports:
        - containerPort: 8000
        env:
        # Fetch sensitive info from the 'django-app-secrets' Secret
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: django-secret-key
        - name: DB_HOST
          value: mysql-service
        - name: DB_NAME
          value: djangodb
        - name: DB_USER
          value: django_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: mysql-app-password
        - name: APP_VERSION # Add a version identifier for demonstration
          value: "blue-v1.0"
        # Optional: Health checks (recommended for production)
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8000
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /readyz
        #     port: 8000
        #   initialDelaySeconds: 10
        #   periodSeconds: 10