pipeline {
    agent {
        docker {
            image 'python:3.9'
            args '-u root' // lets us install OS packages if needed
        }
    }

    environment {
        DJANGO_SETTINGS_MODULE = 'messaging_app.settings.test'
        PYTHON_VENV = 'venv'
    }

    stages {
        stage('Checkout Source Code') {
            steps {
                git credentialsId: 'github-credentials-id',
                    url: 'https://github.com/KimothoKarani/alx-backend-python.git',
                    branch: 'main'
                script {
                    dir('messaging_app') {
                        sh 'ls -la'
                    }
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('messaging_app') {
                    sh """
                        pip install --upgrade pip
                        pip install -r requirements.txt
                    """
                }
            }
        }

        stage('Run Pytest Tests') {
            steps {
                dir('messaging_app') {
                    sh """
                        pytest --junitxml=test-results.xml
                    """
                }
            }
        }

        stage('Publish Test Report') {
            steps {
                dir('messaging_app') {
                    junit 'test-results.xml'
                }
            }
        }
    }
}
